# Generated by Django 5.2.4 on 2025-08-24 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_productivity', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDSParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parameter set name', max_length=100)),
                ('preset_type', models.CharField(choices=[('default', 'Default (Balanced)'), ('time_sensitive', 'Time Sensitive'), ('complexity_focused', 'Complexity Focused'), ('contribution_focused', 'Contribution Focused'), ('custom', 'Custom')], default='default', max_length=20)),
                ('is_system_preset', models.BooleanField(default=False, help_text='System-provided preset')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('torque_alpha', models.FloatField(default=0.001, help_text='Time-weight coefficient (α)')),
                ('torque_beta', models.FloatField(default=0.1, help_text='LOC-weight coefficient (β)')),
                ('torque_gap', models.FloatField(default=30.0, help_text='Torque threshold for starting new batch')),
                ('effort_share_weight', models.FloatField(default=0.25, help_text='Share dimension weight')),
                ('effort_scale_weight', models.FloatField(default=0.15, help_text='Scale dimension weight')),
                ('effort_reach_weight', models.FloatField(default=0.2, help_text='Reach dimension weight')),
                ('effort_centrality_weight', models.FloatField(default=0.2, help_text='Centrality dimension weight')),
                ('effort_dominance_weight', models.FloatField(default=0.15, help_text='Dominance dimension weight')),
                ('effort_novelty_weight', models.FloatField(default=0.05, help_text='Novelty dimension weight')),
                ('effort_speed_weight', models.FloatField(default=0.05, help_text='Speed dimension weight')),
                ('importance_scale_weight', models.FloatField(default=0.3, help_text='Scale dimension weight')),
                ('importance_scope_weight', models.FloatField(default=0.2, help_text='Scope dimension weight')),
                ('importance_centrality_weight', models.FloatField(default=0.15, help_text='Centrality dimension weight')),
                ('importance_complexity_weight', models.FloatField(default=0.15, help_text='Complexity dimension weight')),
                ('importance_type_weight', models.FloatField(default=0.1, help_text='Type dimension weight')),
                ('importance_release_weight', models.FloatField(default=0.1, help_text='Release proximity weight')),
                ('noise_threshold', models.FloatField(default=0.1, help_text='Noise filtering threshold')),
                ('contribution_threshold', models.FloatField(default=0.01, help_text='Minimum meaningful contribution')),
                ('pagerank_damping', models.FloatField(default=0.85, help_text='PageRank damping factor')),
                ('min_churn_for_edge', models.IntegerField(default=2, help_text='Minimum churn for directory graph edge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FDS Parameter Set',
                'verbose_name_plural': 'FDS Parameter Sets',
                'ordering': ['is_system_preset', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fdsanalysis',
            name='parameter_set',
            field=models.ForeignKey(blank=True, help_text='Parameter configuration used for this analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dev_productivity.fdsparameterset'),
        ),
    ]
